/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.cpp
 *  subm:  LoopController
 *  model: RELbotSimple (3)
 *  expmt: RELbotSimple (3)
 *  date:  April 14, 2025
 *  time:  2:37:59 PM
 *  user:  Vakgroep RaM
 *  from:  -
 *  build: 5.1.4.13773
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/


